# Generated by Django 5.1.1 on 2024-10-25 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_purchasedtickets_ticket_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedtickets',
            name='ticketprice',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
