# Generated by Django 5.1.1 on 2024-10-28 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_alter_purchasedtickets_ticketprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='priority',
            field=models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='reply',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='status',
            field=models.CharField(blank=True, choices=[('on-going', 'On Going'), ('resolved', 'Resolved')], max_length=20, null=True),
        ),
    ]
