# Generated by Django 5.1.1 on 2024-10-29 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_purchasedtickets_purchase_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueTicketSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_name', models.CharField(max_length=255, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
