# Generated by Django 5.1.1 on 2024-10-29 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_venueticketsummary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venueticketsummary',
            name='total_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
