# Generated by Django 5.1.1 on 2024-10-29 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_alter_venueticketsummary_total_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalPurchasedTickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticketid', models.IntegerField(blank=True, null=True)),
                ('ticketname', models.CharField(blank=True, max_length=255, null=True)),
                ('ticketprice', models.IntegerField(blank=True, null=True)),
                ('ticket_count', models.IntegerField(default=1)),
                ('purchase_date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
