# Generated by Django 5.1.1 on 2024-11-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_userprofile_first_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedtickets',
            name='credits',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
