# Generated by Django 5.1.3 on 2025-02-27 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_supportticket_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_profile',
            field=models.ImageField(blank=True, default='avatars/avatar.png', null=True, upload_to='avatars/'),
        ),
    ]
