# Generated by Django 5.1.3 on 2025-03-05 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_alter_userprofile_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedtickets',
            name='venue',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='totalpurchasedtickets',
            name='venue',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
